site_dir: build/site
site_name: bluemoss
site_description: A simple way to scrape the web.
site_author: Luca Tabone

repo_name: LucaTabone/bluemoss
repo_url: https://github.com/LucaTabone/bluemoss

strict: true

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  favicon: "favicon.png"
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

extra_javascript:
  - https://unpkg.com/shiki@0.9.6
  - scripts/highlight.js

nav:
  - Home: index.md
