site_dir: build/site
site_name: bluemoss
site_description: A simple way to scrape the web.
site_author: Luca Tabone

repo_name: LucaTabone/bluemoss
repo_url: https://github.com/LucaTabone/bluemoss

strict: true

theme:
  name: material
  palette:
    - scheme: slate
      primary: #20aef5
      accent: #20aef5
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: sunny
      primary: #20aef5
      accent: #20aef5
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  favicon: "favicon.png"
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

extra_javascript:
  - https://unpkg.com/shiki@0.9.6
  - scripts/highlight.js

nav:
  - Home: index.md
  - Real World Examples:
      - Blog Site: real_world_examples/blog.md
      - LinkedIn Profile: real_world_examples/linkedin.md
      - News Site: real_world_examples/news.md
      - E-Commerce Site: real_world_examples/webshop.md